apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-pullsecret-reconciler.fullname" . }}
  labels:
    {{- include "pod-pullsecret-reconciler.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pod-pullsecret-reconciler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pod-pullsecret-reconciler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pod-pullsecret-reconciler.serviceAccountName" . }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WAIT_INTERVAL
              value: "{{ .Values.waitIntervalSeconds }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - /bin/bash
            - /script/reconcile.sh
          volumeMounts:
            - name: script
              mountPath: /script
      volumes:
        - name: script
          configMap:
            name: pod-pullsecret-reconciler-script
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
