apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-pullsecret-reconciler
  labels:
    {{- include "pod-pullsecret-reconciler.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-pullsecret-reconciler
subjects:
- kind: ServiceAccount
  name: {{ include "pod-pullsecret-reconciler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
