apiVersion: v1
kind: ConfigMap
metadata:
  name:  pod-pullsecret-reconciler-script
  labels:
    {{- include "pod-pullsecret-reconciler.labels" . | nindent 4 }}
data:
  reconcile.sh: |-
{{ .Files.Get "reconcile.sh" | indent 4 }}
