apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-pullsecret-reconciler.serviceAccountName" . }}
  labels:
    {{- include "pod-pullsecret-reconciler.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
